apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: backend-feed
        image: younesxchakrani/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        resources:
           requests:
             cpu: 200m
           limits:
             cpu: 500m
        envFrom:
          - configMapRef:
              name: pr3configmap
          - secretRef:
              name: pr3secret
          - secretRef:
              name: your-secret-name