apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backend-feed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-api-feed
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
