apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reverseproxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-reverseproxy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
