apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: younesxchakrani/udagram-reverseproxy:v2
        ports:
        - containerPort: 8080
        resources:
           requests:
             cpu: 200m
           limits:
             cpu: 300m
        envFrom:
          - configMapRef:
              name: pr3configmap
          - secretRef:
              name: pr3secret
          - secretRef:
              name: your-secret-name
